apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dpage/pgadmin4:6.17
          ports:
            - containerPort: 80
          env:
              - name: PGADMIN_DEFAULT_EMAIL
                valueFrom:
                  secretKeyRef:
                    name: backend-secrets
                    key: PG_USER_EMAIL
              - name: PGADMIN_DEFAULT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: pg-admin-secrets
                    key: PG_PASSWORD
              - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
                value: "False"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort

  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80